# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#sudo: false
sudo: required
cache: packages

#apt_packages:

addons:
  apt:
    packages:
      - libxml2-dev
      - libnetcdf-dev
      - netcdf-bin

notifications:
  email:
    on_success: change
    on_failure: change
