language: R
#sudo: false
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libxml2-dev
      - libnetcdf-dev
      - netcdf-bin

notifications:
  email:
    on_success: change
    on_failure: change
