# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#sudo: false
sudo: required
cache: packages

apt_packages:
 - libnetcdf-dev
# - udunits-bin
# - libudunits2-dev
 - netcdf-bin


notifications:
  email:
    on_success: change
    on_failure: change
