language: R
#sudo: false
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libxml2-dev
      - libnetcdf-dev
      - netcdf-bin

# done locally because of tests that conflicts with Travis environment
#r_github_packages:
#  - jimhester/covr
#after_success:
#  - Rscript -e 'covr::codecov()'
