language: R
#sudo: false
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libxml2-dev
      - libnetcdf-dev
      - netcdf-bin

#notifications:
#  email:
#    on_success: change
#    on_failure: change

#r_github_packages:
#  - jimhester/covr
#after_success:
#  - Rscript -e 'covr::codecov()'
